version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: hobii_postgres
    environment:
      POSTGRES_USER: hobii11
      POSTGRES_PASSWORD: 11hobii
      POSTGRES_DB: hobii_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    container_name: hobii_redis
    command: redis-server --requirepass 12hobii
    ports:
      - "6380:6380"
    expose:
      - "6380"
    restart: always

volumes:
  pgdata: